package com.edlplan.osu.support.timing.controlpoint;

public class ControlPoint {
    private double time;

    private boolean autoGenerated;

    public double getTime() {
        return time;
    }

    public void setTime(double time) {
        this.time = time;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

}
