package com.edlplan.osu.support.timing.controlpoint;

public class ControlPoint {
    private int time;

    private boolean autoGenerated;

    public int getTime() {
        return time;
    }

    public void setTime(int time) {
        this.time = time;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

}
