package ru.nsu.ccfit.zuev.osu.game.mods;

public enum GameMod {
    MOD_NOFAIL,
    MOD_AUTO,
    MOD_EASY,
    MOD_HARDROCK,
    MOD_HIDDEN,
    MOD_TRACEABLE,
    MOD_RELAX,
    MOD_AUTOPILOT,
    MOD_DOUBLETIME,
    MOD_NIGHTCORE,
    MOD_HALFTIME,
    MOD_SUDDENDEATH,
    MOD_PERFECT,
    MOD_FLASHLIGHT,
    MOD_PRECISE,
    MOD_SMALLCIRCLE,
    MOD_REALLYEASY,
    MOD_SCOREV2
}
